import type { Recipe } from "./types"

export const mockRecipes: Recipe[] = [
  {
    _id: "1",
    _type: "recipe",
    _createdAt: "2024-01-01",
    _updatedAt: "2024-01-01",
    _rev: "1",
    recipeTitle: "Classic Margherita Pizza",
    description: "Traditional Italian pizza with fresh mozzarella, basil, and tomato sauce",
    cuisine: "Italian",
    meal_type: "Main Course",
    difficulty_level: "Easy",
    prep_time: 15,
    cook_time: 20,
    total_time: 35,
    servings: 4,
    ingredients: [
      "500g pizza dough",
      "200ml tomato sauce",
      "250g fresh mozzarella",
      "Fresh basil leaves",
      "Olive oil",
      "Salt and pepper",
    ],
    instructions: [
      "Preheat oven to 220°C (425°F)",
      "Roll out pizza dough on a floured surface",
      "Spread tomato sauce evenly over the dough",
      "Tear mozzarella and distribute over sauce",
      "Drizzle with olive oil",
      "Bake for 15-20 minutes until crust is golden",
      "Top with fresh basil and serve immediately",
    ],
  },
  {
    _id: "2",
    _type: "recipe",
    _createdAt: "2024-01-02",
    _updatedAt: "2024-01-02",
    _rev: "1",
    recipeTitle: "Thai Green Curry",
    description: "Aromatic and spicy Thai curry with coconut milk and vegetables",
    cuisine: "Thai",
    meal_type: "Main Course",
    difficulty_level: "Medium",
    prep_time: 20,
    cook_time: 25,
    total_time: 45,
    servings: 4,
    ingredients: [
      "2 tbsp green curry paste",
      "400ml coconut milk",
      "300g chicken breast, sliced",
      "200g bell peppers",
      "150g green beans",
      "3 kaffir lime leaves",
      "Fish sauce",
      "Thai basil",
    ],
    instructions: [
      "Heat oil in a wok over medium-high heat",
      "Add curry paste and fry for 1-2 minutes",
      "Pour in coconut milk and stir well",
      "Add chicken and cook until done",
      "Add vegetables and simmer for 10 minutes",
      "Season with fish sauce to taste",
      "Garnish with Thai basil and serve with rice",
    ],
  },
  {
    _id: "3",
    _type: "recipe",
    _createdAt: "2024-01-03",
    _updatedAt: "2024-01-03",
    _rev: "1",
    recipeTitle: "Chocolate Lava Cake",
    description: "Decadent chocolate cake with a molten center",
    cuisine: "French",
    meal_type: "Dessert",
    difficulty_level: "Medium",
    prep_time: 10,
    cook_time: 12,
    total_time: 22,
    servings: 2,
    ingredients: [
      "100g dark chocolate",
      "100g butter",
      "2 eggs",
      "2 egg yolks",
      "25g sugar",
      "25g flour",
      "Pinch of salt",
    ],
    instructions: [
      "Preheat oven to 200°C (400°F)",
      "Melt chocolate and butter together",
      "Whisk eggs, yolks, and sugar until thick",
      "Fold chocolate mixture into eggs",
      "Fold in flour and salt",
      "Pour into buttered ramekins",
      "Bake for 12-14 minutes until edges are firm",
      "Invert onto plates and serve immediately",
    ],
  },
  {
    _id: "4",
    _type: "recipe",
    _createdAt: "2024-01-04",
    _updatedAt: "2024-01-04",
    _rev: "1",
    recipeTitle: "Sushi Rolls",
    description: "Fresh and delicious homemade sushi rolls with various fillings",
    cuisine: "Japanese",
    meal_type: "Main Course",
    difficulty_level: "Hard",
    prep_time: 30,
    cook_time: 0,
    total_time: 30,
    servings: 4,
    ingredients: [
      "2 cups sushi rice",
      "4 nori sheets",
      "200g salmon",
      "1 cucumber",
      "1 avocado",
      "Rice vinegar",
      "Wasabi",
      "Soy sauce",
    ],
    instructions: [
      "Cook sushi rice and season with vinegar",
      "Place nori on bamboo mat",
      "Spread thin layer of rice on nori",
      "Add fillings in a line across the rice",
      "Roll tightly using the mat",
      "Slice with a sharp, wet knife",
      "Serve with wasabi and soy sauce",
    ],
  },
  {
    _id: "5",
    _type: "recipe",
    _createdAt: "2024-01-05",
    _updatedAt: "2024-01-05",
    _rev: "1",
    recipeTitle: "Beef Tacos",
    description: "Flavorful Mexican-style beef tacos with fresh toppings",
    cuisine: "Mexican",
    meal_type: "Main Course",
    difficulty_level: "Easy",
    prep_time: 10,
    cook_time: 15,
    total_time: 25,
    servings: 4,
    ingredients: [
      "500g ground beef",
      "8 taco shells",
      "1 onion, diced",
      "2 tomatoes, diced",
      "Lettuce",
      "Cheddar cheese",
      "Sour cream",
      "Taco seasoning",
    ],
    instructions: [
      "Brown ground beef in a skillet",
      "Add taco seasoning and water",
      "Simmer for 5 minutes",
      "Warm taco shells",
      "Fill shells with beef",
      "Top with lettuce, tomato, and cheese",
      "Serve with sour cream",
    ],
  },
  {
    _id: "6",
    _type: "recipe",
    _createdAt: "2024-01-06",
    _updatedAt: "2024-01-06",
    _rev: "1",
    recipeTitle: "Pasta Carbonara",
    description: "Creamy Italian pasta with bacon and parmesan",
    cuisine: "Italian",
    meal_type: "Main Course",
    difficulty_level: "Easy",
    prep_time: 10,
    cook_time: 20,
    total_time: 30,
    servings: 4,
    ingredients: ["400g spaghetti", "200g pancetta, diced", "4 eggs", "100g parmesan cheese", "Black pepper", "Salt"],
    instructions: [
      "Cook spaghetti in salted boiling water",
      "Fry pancetta until crispy",
      "Whisk eggs with grated parmesan",
      "Drain pasta, reserving 1 cup pasta water",
      "Toss hot pasta with pancetta",
      "Remove from heat and add egg mixture",
      "Toss quickly, adding pasta water as needed",
      "Season with black pepper and serve",
    ],
  },
]
